global using Xunit;
global using FluentAssertions;
global using Moq;
global using Microsoft.EntityFrameworkCore;
global using Pilgrims.PersonalFinances.Core.Models;
global using Pilgrims.PersonalFinances.Core.Models.Enums;
global using Pilgrims.PersonalFinances.Data;
global using Pilgrims.PersonalFinances.Core.Services;
global using Pilgrims.PersonalFinances.Core.Services.Interfaces;